In [1]:
import pandas as pd

In [22]:
df = pd.read_csv('ads.csv', index_col=['date', 'ad_channel'])
df.head(37)

                       impressions  clicks  ad_spend country
date       ad_channel
2026-01-01 Google            12500     245    156.25      RU
           Facebook           9800     156     98.00      UA
           Yandex            15400     308    192.50      KZ
           Instagram          7200     108     72.00      US
           Google            11200     224    140.00      RU
2026-01-02 Facebook          10350     165    103.50      UA
           Yandex            16700     334    208.75      KZ
           Instagram          6850     103     68.50      US
           Google            11900     238    148.75      RU
           TikTok             4500      90     45.00      CN
2026-01-03 Google            13400     268    167.50      RU
           Facebook           9200     138     92.00      UA
           Yandex            14250     285    178.13      KZ
           Instagram          7800     117     78.00      US
           Google            10800     216    135.00      RU
2026-01-04 Facebook          11500     184    115.00      UA
           Yandex            16100     322    201.25      KZ
           Instagram          7100     106     71.00      US
           TikTok             5200     104     52.00      CN
           Google            12750     255    159.38      RU
2026-01-05 Yandex            14800     296    185.00      KZ
           Facebook           9500     152     95.00      UA
           Google            13200     264    165.00      RU
           Instagram          7400     111     74.00      US
           TikTok             4800      96     48.00      CN
2026-01-06 Google            14100     282    176.25      RU
           Yandex            15500     310    193.75      KZ
           Facebook           9850     157     98.50      UA
           Instagram          6950     104     69.50      US
2026-01-07 Google            12300     246    153.75      RU
           TikTok             5100     102     51.00      CN
           Yandex            16900     338    211.25      KZ
           Facebook          10700     171    107.00      UA
           Instagram          7650     115     76.50      US
2026-01-08 Google            13600     272    170.00      RU
           Yandex            15200     304    190.00      KZ
           Facebook          11200     179    112.00      UA

In [ ]:
# df.loc['2026-01-01'].loc['Google'] # Подмножество строк и обращаемся дальше к ним как в составных данных

In [ ]:
# Агрегирование серий
# df.dtypes # Смотрим типы данных в дф
# df['ad_spend'].sum() # Сумма серии 
# df['ad_spend'].count() # Подсчет количества элементов серии
# df['ad_spend'].min()
# df['ad_spend'].max()
# df['ad_spend'].mean() # Среднее арифметическое 
# df['ad_spend'].std() # Стандартное отклонение 
# df['ad_spend'].median()
# df['ad_spend'].quantile() 
# df['ad_spend'].unique() # Массив уникальных значений 
# df['ad_spend'].nunique() # Считает количество уникальных значений 
# df['ad_spend'].idxmax() # Находит индекс максимального значения

In [ ]:
# Агрегирование датафреймов 
# df.sum() # Пойдет по каждой колонке, и если там можно применить sum, то применит 
# df.sum()['impressions'] # Здесь суммирует определенную колонку
# df.sum(axis='columns') # Сумму можно применять как построчно, так и по колонкам. По оси!

date        ad_channel  country
2026-01-01  Google      RU         12901.25
            Facebook    UA         10054.00
            Yandex      KZ         15900.50
            Instagram   US          7380.00
            Google      RU         11564.00
                                     ...
2026-01-31  Google      RU         14300.13
            TikTok      CN          4686.50
            Yandex      KZ         16674.88
            Facebook    UA         11286.00
            Instagram   US          7585.00
Length: 146, dtype: float64

In [37]:
# Группировка 
df.groupby(['country']).sum() # Получили дф с индексом 'Страна' и значние - это сумма таких то значений по стране
# Сюда можно применять все те же функции агрегации
# df.groupby(['ad_channel'])[['impressions']].sum()
# df.groupby(['ad_channel']).agg( # В функцию agg запихиваем словарь, где ключ это название колонки, а значение это список из функций, которых мы хотим применить к колонке
#     {'impressions': ['sum', 'count'],
#      'ad_spend': ['sum', 'mean']}
# )

         impressions  clicks  ad_spend
country
CN             98100    1962    981.00
KZ            480500    9610   6006.30
RU            431000    8615   5387.56
UA            326550    5211   3265.50
US            228050    3424   2280.50

In [ ]:
df.groupby(['ad_channel']).agg(
    total_impressions = ('impressions', 'sum'), # Здесь называем колонки как мы хотим, и туда передаем кортеж из 1 - колонка, 2 - агрегирующая функция
    avg_daily_spend = ('impressions', 'mean')
)

            total_impressions  avg_daily_spend
ad_channel
Facebook               326550     10533.870968
Google                 431000     13060.606061
Instagram              228050      7356.451613
TikTok                  98100      4905.000000
Yandex                 480500     15500.000000

In [38]:
rev_per_click ={
    'RU': 0.04,
    'UA': 0.35,
    'KZ': 0.4,
    'US': 0.07,
    'CN': 0.5
}

def calculate_roi(group): # Передаем в функцию наш маленький дф(группу)
    country = group.reset_index()['country'].iloc[0] # Взяли 1-ое значение какой-то колонки и присвоили переменной 
    clicks = group['clicks'].sum() # Далее агрегировали колонку нашего маленького дф - просуммировали и записали в переменную
    ad_spend = group['ad_spend'].sum() # То же самое
    revenue = clicks * rev_per_click[country] # Умножили клики на rpc каждой страны в нашем словаре 
    roi = revenue / ad_spend # Результат
    return roi # Вернули результат


df.groupby('country').apply(calculate_roi) # Здесь берем наш дф, группируем его по определенному значению(в нашем случаем - это страна(бывшая колонка))
# Далее применяем нашу кастомную функцию к нашему сгруппированому дф
# Условно, group - это маленький датафрейм

/var/folders/33/zz2lcn0n425205ytsgcpchk00000gn/T/ipykernel_1259/3328540438.py:18: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('country').apply(calculate_roi) # Здесь берем наш дф, группируем его по определенному значению(в нашем случаем - это страна(бывшая колонка))

country
CN    1.000000
KZ    0.639995
RU    0.063962
UA    0.558521
US    0.105100
dtype: float64

In [ ]:
# Сортировка 
# .sort_values() # Сорировка по значениям 
# .sort_index() # Сортировка по индексам
df.groupby('country').apply(calculate_roi).sort_values(ascending=False)

/var/folders/33/zz2lcn0n425205ytsgcpchk00000gn/T/ipykernel_1259/1075161577.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('country').apply(calculate_roi).sort_values(ascending=False)

country
CN    1.000000
KZ    0.639995
UA    0.558521
US    0.105100
RU    0.063962
dtype: float64

In [ ]:
df.sort_values(by='ad_spend', ascending=False) # Соритируем по значениям определенной колонки

                       impressions  clicks  ad_spend country
date       ad_channel
2026-01-28 Yandex            16900     338    211.25      KZ
2026-01-07 Yandex            16900     338    211.25      KZ
2026-01-16 Yandex            16750     335    209.38      KZ
2026-01-02 Yandex            16700     334    208.75      KZ
2026-01-22 Yandex            16500     330    206.25      KZ
...                            ...     ...       ...     ...
2026-01-08 TikTok             4650      93     46.50      CN
2026-01-23 TikTok             4600      92     46.00      CN
2026-01-31 TikTok             4550      91     45.50      CN
2026-01-02 TikTok             4500      90     45.00      CN
2026-01-17 TikTok             4450      89     44.50      CN

[146 rows x 4 columns]

In [ ]:
(
    df # С помощью скобок, можно удобно писать нагроможденные функции на новой строке 
    .groupby('country')
    .apply(calculate_roi)
    .sort_values(ascending=False)
)