In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('daily_visitors_dynamic.csv')
df.head()

         date   ad_channel  daily_visitors
0  2026-01-01       google              52
1  2026-01-01     facebook              50
2  2026-01-01      youtube              55
3  2026-01-01    instagram              53
4  2026-01-01  influencers              51

In [10]:
df.groupby('date').sum()

                                           ad_channel  daily_visitors
date
2026-01-01  googlefacebookyoutubeinstagraminfluencers             261
2026-01-02  googlefacebookyoutubeinstagraminfluencers             271
2026-01-03  googlefacebookyoutubeinstagraminfluencers             280
2026-01-04  googlefacebookyoutubeinstagraminfluencers             290
2026-01-05  googlefacebookyoutubeinstagraminfluencers             300
2026-01-06  googleyoutubefacebookinstagraminfluencers             310
2026-01-07  googlefacebookyoutubeinstagraminfluencers             320
2026-01-08  instagramgooglefacebookyoutubeinfluencers             330
2026-01-09  googleyoutubefacebookinstagraminfluencers             340
2026-01-10  googlefacebookinstagramyoutubeinfluencers             350
2026-01-11  googleyoutubefacebookinstagraminfluencers             360
2026-01-12  googleinstagramfacebookyoutubeinfluencers             370
2026-01-13  googlefacebookyoutubeinstagraminfluencers             380
2026-01-14  googlefacebookyoutubeinstagraminfluencers             390
2026-01-15  googleinstagramfacebookyoutubeinfluencers             400
2026-01-16  googleyoutubefacebookinstagraminfluencers             410
2026-01-17  googlefacebookinstagramyoutubeinfluencers             420
2026-01-18  googleyoutubefacebookinstagraminfluencers             430
2026-01-19  googlefacebookinstagramyoutubeinfluencers             440
2026-01-20  googleyoutubefacebookinstagraminfluencers             450
2026-01-21  googlefacebookinstagramyoutubeinfluencers             460
2026-01-22  googleyoutubefacebookinstagraminfluencers             470
2026-01-23  googlefacebookinstagramyoutubeinfluencers             480
2026-01-24  googleyoutubefacebookinstagraminfluencers             489
2026-01-25  googlefacebookinstagramyoutubeinfluencers             494
2026-01-26  googleyoutubefacebookinstagraminfluencers             497
2026-01-27  googlefacebookinstagramyoutubeinfluencers             492
2026-01-28  googleyoutubefacebookinstagraminfluencers             494
2026-01-29  googlefacebookinstagramyoutubeinfluencers             494
2026-01-30  googleyoutubefacebookinstagraminfluencers             497
2026-01-31  googlefacebookinstagramyoutubeinfluencers             495