In [ ]:
import pandas as pd

In [14]:
orders = pd.read_csv('practice/orders.csv')
orders.head()

   order_id  user_idi  order_amount order_created_dt
0       768      2457          6440       2020-02-14
1       769      1486          6440       2020-02-16
2       770      2473          6440       2020-02-19
3       771      2132          6440       2020-02-21
4       772      2132         19900       2020-02-27

In [13]:
costs = pd.read_csv('practice/costs.csv')
costs.head()

         date         source     campaign    cost
0  2020-01-01  yandex_direct  gnrl|445275  130.08
1  2020-01-01  yandex_direct  gnrl|953233  117.67
2  2020-01-02             fb  gnrl|755263   64.42
3  2020-01-02             fb   lal|772023  197.11
4  2020-01-02             vk   lal|727027  153.02

In [26]:
daily_revenue = orders.groupby('order_created_dt').agg(revenue = ('order_amount', 'sum'))
daily_revenue.head()

                  revenue
order_created_dt
2020-02-14           6440
2020-02-16           6440
2020-02-19           6440
2020-02-21           6440
2020-02-27          19900

In [27]:
daily_spend = costs.groupby('date').agg(spend = ('cost', 'sum'))
daily_spend.head()

              spend
date
2020-01-01   247.75
2020-01-02   414.55
2020-01-03  1041.98
2020-01-04  1412.45
2020-01-05  1009.86

In [ ]:
(
    daily_revenue
    .merge(daily_spend, how='outer', left_index=True, right_index=True)
    .fillna(0)
).head(50)
# У нас получился дф, где иногда дневная выручка = 0, а иногда дневные траты = 0. Именно поэтому здесь подходит полный джоин, остальные джоины не включили бы эти дни в свои датафреймы

            revenue    spend
2020-01-01      0.0   247.75
2020-01-02      0.0   414.55
2020-01-03      0.0  1041.98
2020-01-04      0.0  1412.45
2020-01-05      0.0  1009.86
2020-01-06      0.0  1541.44
2020-01-07      0.0  1294.97
2020-01-08      0.0  2762.61
2020-01-09      0.0  1390.63
2020-01-10      0.0  2462.01
2020-01-11      0.0  1901.77
2020-01-12      0.0  2345.18
2020-01-13      0.0  2185.36
2020-01-14      0.0  2880.03
2020-01-15      0.0  2655.70
2020-01-16      0.0  2398.51
2020-01-17      0.0  2195.39
2020-01-18      0.0  3315.34
2020-01-19      0.0  2336.46
2020-01-20      0.0  3275.78
2020-01-21      0.0  1416.30
2020-01-22      0.0  2360.71
2020-01-23      0.0  2644.31
2020-01-24      0.0  3638.21
2020-01-25      0.0  1455.73
2020-01-26      0.0  2630.08
2020-01-27      0.0  1749.02
2020-01-28      0.0  3461.65
2020-01-29      0.0  1833.90
2020-01-30      0.0  1754.00
2020-01-31      0.0  3391.86
2020-02-01      0.0  2929.53
2020-02-02      0.0  2527.96
2020-02-03      0.0  1319.73
2020-02-04      0.0  2247.31
2020-02-05      0.0  4722.82
2020-02-06      0.0  3038.32
2020-02-07      0.0  1722.15
2020-02-08      0.0  2607.62
2020-02-09      0.0  2164.30
2020-02-10      0.0  2797.78
2020-02-11      0.0  2449.63
2020-02-12      0.0  2407.05
2020-02-13      0.0  2674.81
2020-02-14   6440.0  2560.12
2020-02-15      0.0  2362.22
2020-02-16   6440.0  1926.01
2020-02-17      0.0  2659.65
2020-02-18      0.0  1627.01
2020-02-19   6440.0  2214.80

In [ ]:
# users = pd.read_csv('practice/users.csv')
# users.drop_duplicates(subset=['user_id'], inplace=True)
# users.head()

In [ ]:
# (
#    users
#    .merge(orders, how='outer', left_on='user_id', right_on='user_idi') # outer(Внешний или полный джоин) - отличается тем, что в результатах оставляет все строки обоих дф(без соотвествия строк)
# )

In [ ]:
orders['created_at'].str.slice(0,10) # Здесь достаем даты из таймстемпов(с помощью slice указываем колоичество определенных симоволов, которые достаем из значения ячейки)
# Также даты здесь остаются текстом, а по хорошему, даты должны оставаться в формате даты