In [2]:
import pandas as pd

In [19]:
orders = pd.read_csv('practice/orders.csv')
orders.head()

   order_id  user_idi  order_amount order_created_dt
0       768      2457          6440       2020-02-14
1       769      1486          6440       2020-02-16
2       770      2473          6440       2020-02-19
3       771      2132          6440       2020-02-21
4       772      2132         19900       2020-02-27

In [20]:
users = pd.read_csv('practice/users.csv')
users.drop_duplicates(subset=['user_id'], inplace=True)
users.head()

,user_id,user_email,user_registration_dt,user_city,client_id
0,1425,anilidic1822@outlook.com,2020-06-23,Екатеринбург,1120163048-362459827
1,1429,bornagain1847@gmail.com,2020-08-15,Санкт-Петербург,830333202-483914880
2,1434,engluts2049@yahoo.com,2020-03-07,Новосибирск,28897314-329863990
3,1436,hedgehog2019@live.com,2020-09-04,Москва,1238119072-242362229
4,1439,chinook1914@yahoo.com,2020-06-29,Москва,977210465-54763416

In [22]:
list((users # Внутренний джоин двух таблиц
 .merge(orders, how='inner', left_on='user_id', right_on='user_idi') # Внутренний джоин оставлять только те строки, которые присутствуют в обеих таблицах
 ['user_email']
 .unique()
 ))

['snakemouths1913@outlook.com',
 'metaluminic1838@gmail.com',
 'guidage1946@yahoo.com',
 'larcenies1978@live.com',
 'socked1859@live.com',
 'headsmen2057@protonmail.com',
 'designers1919@outlook.com',
 'unniceness2032@yahoo.com',
 'crista2005@outlook.com',
 'arylate1988@outlook.com',
 'wingy1831@outlook.com',
 'hypoergic2022@protonmail.com',
 'protrusile1899@protonmail.com',
 'aphotic1957@gmail.com',
 'earrings2066@live.com',
 'aceology2055@live.com',
 'wimple2054@live.com',
 'egret1905@yahoo.com',
 'draughtsman1853@outlook.com',
 'animated1825@outlook.com',
 'nonslipping2019@protonmail.com',
 'copyist2045@live.com',
 'overspeculation1986@live.com',
 'breeds1965@protonmail.com',
 'unalimentative1821@protonmail.com',
 'paleichthyology1995@yahoo.com',
 'unrooted2033@gmail.com',
 'effectible2030@outlook.com',
 'preprudently1835@live.com',
 'dashed1922@protonmail.com',
 'scurry2000@yandex.com',
 'tafia1960@outlook.com',
 'evacuator1840@gmail.com',
 'parallelized2013@live.com',
 'toruloid1840@yandex.com',
 'lactim2031@yandex.com',
 'memoir1840@live.com',
 'boatly1986@yahoo.com',
 'paterero2044@gmail.com',
 'enterocoele2035@yandex.com',
 'boreades1879@gmail.com',
 'drover1928@yahoo.com',
 'arcane1978@live.com',
 'churchill1885@protonmail.com',
 'caplin1859@outlook.com',
 'cichlid1910@outlook.com',
 'phytosauria1803@yandex.com',
 'toelike1826@live.com',
 'berkowitz1872@yahoo.com',
 'ineradicability1847@gmail.com',
 'billowy1911@protonmail.com',
 'philepitta2003@yahoo.com',
 'breaklist1882@outlook.com',
 'arulo1980@gmail.com',
 'crab2005@yahoo.com',
 'allegiances2021@yandex.com',
 'greengage1979@yandex.com',
 'borneo1867@protonmail.com',
 'sabed2022@yahoo.com',
 'phrenetically1806@protonmail.com',
 'bounder2055@yandex.com',
 'paratrophy1946@outlook.com',
 'unties1952@live.com',
 'kickxia1917@protonmail.com',
 'acromegalies1981@outlook.com',
 'skellum1924@yahoo.com',
 'jay1913@gmail.com',
 'inducing1959@outlook.com',
 'bommer2036@live.com',
 'aboriginal1973@protonmail.com',
 'polyphone2023@yahoo.com',
 'earwig2026@yahoo.com',
 'encloud1849@outlook.com',
 'nympholept1928@yahoo.com',
 'brimborion2067@yahoo.com',
 'transplace1890@yandex.com',
 'eyetooth2010@live.com',
 'compress1812@protonmail.com',
 'zaffre1847@gmail.com',
 'uranolatry1951@outlook.com',
 'analyst1999@outlook.com',
 'cheng2050@outlook.com',
 'baht1943@yahoo.com',
 'belanda2020@live.com',
 'basnet1998@yandex.com',
 'aggest2018@protonmail.com',
 'alten1981@live.com',
 'alvine1867@protonmail.com',
 'boilerman1942@gmail.com',
 'uppercut2052@live.com',
 'tovarish2024@outlook.com',
 'mule1948@live.com',
 'sardine1954@yandex.com',
 'prosobranch1854@yandex.com',
 'broch1813@outlook.com',
 'aback2035@live.com',
 'cingulate1944@gmail.com',
 'imbonity1928@outlook.com',
 'coumara1908@outlook.com',
 'adminstration1815@gmail.com',
 'hare1998@yahoo.com',
 'navite1856@live.com',
 'headwaiter2059@yandex.com',
 'nincum1923@protonmail.com',
 'armour1969@gmail.com',
 'sylvin1819@live.com',
 'letdown2046@protonmail.com',
 'wingy1888@yandex.com',
 'avgas1858@gmail.com',
 'pedicab1924@outlook.com',
 'damocles1866@gmail.com',
 'penicilliform2012@outlook.com',
 'lactim1848@live.com',
 'seaside1953@yandex.com',
 'industrochemical1900@gmail.com',
 'poohing2036@yahoo.com',
 'eulalia1917@outlook.com',
 'galagos1966@yandex.com',
 'brennand1821@yandex.com',
 'caxton1955@yandex.com',
 'athletics1843@yandex.com',
 'doolittle1810@yandex.com',
 'hiddenmost1859@outlook.com',
 'numbat1859@live.com',
 'buffoonish1947@yandex.com',
 'deaved2058@outlook.com',
 'apologies1981@yahoo.com',
 'succursal2011@outlook.com',
 'sawbucks1999@yandex.com',
 'addiction1959@yandex.com',
 'hygenics2010@live.com',
 'nubigenous1943@gmail.com',
 'croquette1874@yandex.com',
 'dayton1902@yandex.com',
 'decoupage2003@live.com',
 'symmetrically2061@protonmail.com',
 'wronghead1880@yandex.com',
 'astral1847@protonmail.com',
 'jarbird2017@outlook.com',
 'unsuperstitiousness1965@live.com',
 'jovicentrical1926@protonmail.com',
 'latipennate2013@yandex.com',
 'clients1907@yahoo.com',
 'algal1852@yahoo.com',
 'tromometric2014@yandex.com',
 'fermentitious2046@yandex.com',
 'irradiation1866@live.com',
 'cercle1954@gmail.com',
 'tastier1846@yahoo.com',
 'bronze2034@yandex.com',
 'recalcitrating1869@yandex.com',
 'flounder1834@yandex.com',
 'fuligulinae1985@gmail.com',
 'dovelet1877@yahoo.com',
 'polyparies1840@live.com',
 'infectionist2052@gmail.com',
 'adenine1998@live.com',
 'swan1900@gmail.com',
 'arsenium1959@live.com',
 'religionists1896@gmail.com',
 'agnoite1932@yandex.com',
 'us1995@outlook.com',
 'oxides2004@yandex.com',
 'developed1987@yandex.com',
 'mastiff1956@yandex.com',
 'juliennes1855@live.com',
 'ruttily1967@yahoo.com',
 'hypoergic1888@outlook.com',
 'creating2018@yahoo.com',
 'meteorology1861@gmail.com',
 'equiperiodic1802@yahoo.com',
 'retying1873@live.com',
 'dalt2044@gmail.com',
 'plasmid1966@outlook.com',
 'devastating2020@outlook.com',
 'kiwi1883@protonmail.com',
 'displeasingness1871@protonmail.com',
 'spratted1921@yandex.com',
 'donatistical1867@live.com',
 'peculiarise1959@gmail.com',
 'midwifes1821@outlook.com',
 'anamorphose2050@gmail.com',
 'conservatives2004@live.com',
 'planted1827@protonmail.com',
 'delage2004@yandex.com',
 'subjicible1948@live.com',
 'milliard1853@outlook.com',
 'animated1950@outlook.com',
 'transact2009@live.com',
 'anticlassicalist2015@yahoo.com',
 'trajects2004@live.com',
 'messor1891@outlook.com',
 'arriba1882@protonmail.com',
 'buffoonish2054@live.com',
 'bigwig2060@yandex.com',
 'deceive1963@yandex.com',
 'aviation1838@gmail.com',
 'aural2003@protonmail.com',
 'craving1862@yahoo.com',
 'decimate2066@live.com',
 'sciomachiology1960@yandex.com',
 'dependent1874@gmail.com',
 'rebukable2019@protonmail.com',
 'cheetham1964@live.com',
 'collodion1869@yahoo.com',
 'colloid1974@live.com',
 'eladio1836@protonmail.com',
 'bloodhound1980@yandex.com',
 'daleth1950@yandex.com',
 'abridged1849@live.com']

In [ ]:
# (. # inner join - операция, которая позволяет объеденить несколько датафреймов по какому-то набору колонок и в результате оставляет только те строки, которые есть в обоих дф. По сути - полное пересечение
#     orders
#     .merge(line_items, how='inner', on='payment_id')
#     .merge(items, how='inner', left_on='item_id', right_index=True)
#     .groupby('item_id')
#     .agg({'title': 'first', 'sub_total': 'sum'})
# ).sum()

515