In [1]:
import pandas as pd

In [10]:
orders = pd.read_csv('practice/orders.csv')
orders.head()

   order_id  user_idi  order_amount order_created_dt
0       768      2457          6440       2020-02-14
1       769      1486          6440       2020-02-16
2       770      2473          6440       2020-02-19
3       771      2132          6440       2020-02-21
4       772      2132         19900       2020-02-27

In [9]:
users = pd.read_csv('practice/users.csv')
users.drop_duplicates(subset=['user_id'], inplace=True)
users.head()

,user_id,user_email,user_registration_dt,user_city,client_id
0,1425,anilidic1822@outlook.com,2020-06-23,Екатеринбург,1120163048-362459827
1,1429,bornagain1847@gmail.com,2020-08-15,Санкт-Петербург,830333202-483914880
2,1434,engluts2049@yahoo.com,2020-03-07,Новосибирск,28897314-329863990
3,1436,hedgehog2019@live.com,2020-09-04,Москва,1238119072-242362229
4,1439,chinook1914@yahoo.com,2020-06-29,Москва,977210465-54763416

In [ ]:
# (
#     users
#     .merge(orders, how='left', left_on='user_id', right_on='user_idi') # Левый джоин - выдает нам дф где есть все строки(без исключения) левого датафрейма, даже если нет соответствующих строк в правом датафрейме 
#     .query('order_id.isna()') # Отличная проверка столбцов на значения, возвращает дф с выполненным условием 
#     ['user_email'] 
# ) 
# .isna() - Проверка на пустоту

0           anilidic1822@outlook.com
1            bornagain1847@gmail.com
2              engluts2049@yahoo.com
3              hedgehog2019@live.com
4              chinook1914@yahoo.com
                   ...
565        tewing1986@protonmail.com
566            cassat2058@yandex.com
567             kloof1851@yandex.com
568    enormously1869@protonmail.com
570        coquitlam1862@outlook.com
Name: user_email, Length: 305, dtype: object

In [18]:
(
    users
    .merge(orders, how='left', left_on='user_id', right_on='user_idi')
    .groupby('user_id')
    .agg({'user_email': 'first', 'order_amount': 'sum'})
)

                            user_email  order_amount
user_id
1425          anilidic1822@outlook.com           0.0
1429           bornagain1847@gmail.com           0.0
1434             engluts2049@yahoo.com           0.0
1436             hedgehog2019@live.com           0.0
1439             chinook1914@yahoo.com           0.0
...                                ...           ...
3111              kloof1851@yandex.com           0.0
3116     enormously1869@protonmail.com           0.0
3119             daleth1950@yandex.com        6440.0
3124         coquitlam1862@outlook.com           0.0
3125             abridged1849@live.com        6440.0

[515 rows x 2 columns]